on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SonarQube check
    steps:
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
      - name: Run sonarqube
        env:
          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.sources=.
          -Dsonar.host.url=http://issue.pagekite.me
          -Dsonar.projectKey=oxc
          -Dsonar.scm.enabled=true
          -Dsonar.scm.provider=tfvc
